name: Test i Push Automàtic

on:
  schedule:
    - cron: '*/5 * * * *'   # Cada 5 minuts
  workflow_dispatch:        # Permet executar-ho manualment

permissions:
  contents: write           # Necessari per fer push

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositori
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instal·lar dependències
        run: pip install requests

      - name: Executar el script
        run: python temps.py

      - name: Fer commit i push dels resultats
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add temp_*.json
          git commit -m "Afegir arxiu temperatures del dia $(date +%Y%m%d)" || echo "No hi ha canvis"
          git push
